### PR TITLE
Fixed list update

### PR DESCRIPTION
**Pull request by fidlip**
When list  update has been invoked, nothing happened, map method was not executed -> substituted to forEach method

### CODE REVIEW

**Comment by k-paxian** [comment]
Hey @fidlip
Thank you for contributing, could you please provide test use case for that issue.

**Comment by fidlip** [comment]
Hi, it will be little bit tricky to extract it from our code. I could try but I believe it can be demonstrated with this simple code:
```
void main() {

  List<String> list1 = ["foo", "bar"];
  List<String> list2 = ["xyz", "abc", "def"];
  
  list2.map((item) => list1.add(item));

  print("firstTry: list1= $list1");     // this will print: "firstTry: list1= [foo, bar]"

  
  list2.forEach((item) => list1.add(item));

  print("secondTry: list1= $list1");    // but this print correctly: "secondTry: list1= [foo, bar, xyz, abc, def]"

}

```

**Comment by k-paxian** [comment]
release 1.1.8 should fix that. Please confirm

**Comment by fidlip** [comment]
Thanks you, I will test tomorrow and let you know, if there will be any problem.

**Pull request closed without merging**
